[project]
name = "hashicorp-vault-docker-iac"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "pulumi>=3.0.0,<4.0.0",
    "pulumi-koyeb==0.1.11",
    "black==25.1.0"
]
